### ISSUE TITLE
repo name nit: it'd be nice if this were simply w3c/png

### ISSUE THREAD

**Issue by hober** [w3c/png#450]
though I suppose that could be easily confused with `w3c/ping`, sigh.

**Comment by Crissov** [comment]
We have learned to live with `csswg-drafts` instead of `css`, so 🤷‍♂️

**Comment by ProgramMax** [comment]
GitHub does allow renaming repos, I think.
I'm okay either way. Someone who knows what W3C is will immediately understand "/png" is the spec. So "/PNG-spec" is redundant to them. But to someone who doesn't know, "/png" might be assumed as some decoder with lots of intricate docs. To them, I think "/PNG-spec" is more useful.

I think overall I prefer "/PNG-spec" (or all lower case). But I'm okay with a change if people want.

**Comment by annevk** [comment]
FWIW, I agree that this rename makes sense and I'm not too worried about confusion with PING. At least I haven't seen anyone make that mistake.

Consistency is another reason to do this. Nothing else has "-spec" as a suffix.

**Comment by ProgramMax** [comment]
Sounds good. I'll look into renaming it w3c/png.

**Comment by ProgramMax** [comment]
I am unable to rename the repo. I believe a W3C member must do it.

**Comment by svgeesus** [comment]
okay, it is `w3c/png` now
